# Generated by Django 4.0 on 2024-08-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('voltage_l1_l2', models.FloatField()),
                ('voltage_l1_l2_dev', models.FloatField()),
                ('voltage_l3_l1', models.FloatField()),
                ('voltage_l3_l1_dev', models.FloatField()),
                ('voltage_l2_l3', models.FloatField()),
                ('voltage_l2_l3_dev', models.FloatField()),
                ('voltage_l1', models.FloatField()),
                ('voltage_l1_dev', models.FloatField()),
                ('voltage_l2', models.FloatField()),
                ('voltage_l2_dev', models.FloatField()),
                ('voltage_l3', models.FloatField()),
                ('voltage_l3_dev', models.FloatField()),
                ('current_l1', models.FloatField()),
                ('current_l1_dev', models.FloatField()),
                ('current_l2', models.FloatField()),
                ('current_l2_dev', models.FloatField()),
                ('current_l3', models.FloatField()),
                ('current_l3_dev', models.FloatField()),
                ('power_factor', models.FloatField()),
                ('power_factor_dev', models.FloatField()),
                ('frequency_1', models.FloatField()),
                ('frequency_1_dev', models.FloatField()),
                ('frequency_2', models.FloatField()),
                ('frequency_2_dev', models.FloatField()),
                ('frequency_3', models.FloatField()),
                ('frequency_3_dev', models.FloatField()),
                ('dc_input_voltage', models.FloatField()),
                ('dc_input_voltage_dev', models.FloatField()),
                ('dc_input_current', models.FloatField()),
                ('dc_input_current_dev', models.FloatField()),
                ('dc_input_power', models.FloatField()),
                ('dc_input_power_dev', models.FloatField()),
                ('temperature', models.FloatField()),
                ('temperature_dev', models.FloatField()),
                ('solar_irradiance_1', models.FloatField()),
                ('solar_irradiance_1_dev', models.FloatField()),
                ('solar_irradiance_2', models.FloatField()),
                ('solar_irradiance_2_dev', models.FloatField()),
                ('solar_irradiance_3', models.FloatField()),
                ('solar_irradiance_3_dev', models.FloatField()),
                ('active_power_01', models.FloatField()),
                ('active_power_01_dev', models.FloatField()),
                ('active_power_02', models.FloatField()),
                ('active_power_02_dev', models.FloatField()),
                ('active_power_03', models.FloatField()),
                ('active_power_03_dev', models.FloatField()),
                ('reference_power_01', models.FloatField()),
                ('reference_power_01_dev', models.FloatField()),
                ('reference_power_02', models.FloatField()),
                ('reference_power_02_dev', models.FloatField()),
                ('reference_power_03', models.FloatField()),
                ('reference_power_03_dev', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
