# forms.py

from django import forms

class InverterForm(forms.Form):
    name = forms.CharField(max_length=100)
    voltage_l1_l2 = forms.FloatField()
    voltage_l1_l2_dev = forms.FloatField()
    voltage_l3_l1 = forms.FloatField()
    voltage_l3_l1_dev = forms.FloatField()
    voltage_l2_l3 = forms.FloatField()
    voltage_l2_l3_dev = forms.FloatField()
    voltage_l1 = forms.FloatField()
    voltage_l1_dev = forms.FloatField()
    voltage_l2 = forms.FloatField()
    voltage_l2_dev = forms.FloatField()
    voltage_l3 = forms.FloatField()
    voltage_l3_dev = forms.FloatField()
    current_l1 = forms.FloatField()
    current_l1_dev = forms.FloatField()
    current_l2 = forms.FloatField()
    current_l2_dev = forms.FloatField()
    current_l3 = forms.FloatField()
    current_l3_dev = forms.FloatField()
    power_factor = forms.FloatField()
    power_factor_dev = forms.FloatField()
    frequency_1 = forms.FloatField()
    frequency_1_dev = forms.FloatField()
    frequency_2 = forms.FloatField()
    frequency_2_dev = forms.FloatField()
    frequency_3 = forms.FloatField()
    frequency_3_dev = forms.FloatField()
    dc_input_voltage = forms.FloatField()
    dc_input_voltage_dev = forms.FloatField()
    dc_input_current = forms.FloatField()
    dc_input_current_dev = forms.FloatField()
    dc_input_power = forms.FloatField()
    dc_input_power_dev = forms.FloatField()
    temperature = forms.FloatField()
    temperature_dev = forms.FloatField()
    solar_irradiance_1 = forms.FloatField()
    solar_irradiance_1_dev = forms.FloatField()
    solar_irradiance_2 = forms.FloatField()
    solar_irradiance_2_dev = forms.FloatField()
    solar_irradiance_3 = forms.FloatField()
    solar_irradiance_3_dev = forms.FloatField()
    active_power_01 = forms.FloatField()
    active_power_01_dev = forms.FloatField()
    active_power_02 = forms.FloatField()
    active_power_02_dev = forms.FloatField()
    active_power_03 = forms.FloatField()
    active_power_03_dev = forms.FloatField()
    reference_power_01 = forms.FloatField()
    reference_power_01_dev = forms.FloatField()
    reference_power_02 = forms.FloatField()
    reference_power_02_dev = forms.FloatField()
    reference_power_03 = forms.FloatField()
    reference_power_03_dev = forms.FloatField()
